[project]
title = "Action Movie Data"
version = "0.1.0"
port = 8501
slug = "Action-Movie-Data"  
entrypoint = "hello.py"    

[branding]
name = "Action Movie Data"
logo = "images/movie.png"
favicon = "images/tools.ico"
primaryColor = "#808080"

[data.movie]
type = "csv"
path = "data/movie.csv"

[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"